api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.views import *

router = routers.DefaultRouter()
router.register(r'folder', FolderViewSet)
router.register(r'sheet', SheetViewSet)
router.register(r'cell', CellViewSet)
router.register(r'file', FileItemViewSet)
router.register(r'tag', TagViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

courses/urls.py
from django.contrib import admin
from django.urls import path
from courses.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome),
    path('welcome/', welcome),
    path('add_course/', add_course),
    path('add_instructor/', add_instructor),
    path('save_course/', save_course),
    path('save_instructor/', save_instructor)

]

klazor/urls.py
"""Klazor URL Configuration. """
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from klazor.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Administration views
    path('admin/', admin.site.urls),

    # Authentication views
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='pages/welcome.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', welcome, name='welcome'),
    url(r'^register/$', register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('folder/<int:id>/', view_folder, name='folder'),
    path('folder/editor/<int:id>/sheet/<int:sheet_id>', view_folder_editor, name='folder-editor'),
    path('sheet/<int:id>/', view_sheet, name='sheet'),
    path('folder/<int:id>/sheet/new/', add_sheet, name='add-sheet'),
    path('sheet/<int:id>/save/', save_sheet, name='save-sheet'),
    path('sheet/<int:id>/cell/save/', save_cell, name='save-cell'),
    path('item/move/<int:id>/into/<int:destination_id>', move_item, name='move-item'),
    path('item/delete/<int:id>/', delete_item, name='delete-item'),
    path('folder/delete/<int:id>/', delete_folder, name='delete-folder'),
    path('folder/move/<int:id>/into/<int:destination_id>', move_folder, name='move-folder'),
    path('folder/rename/<int:id>/', rename_folder, name='rename-folder'),
    path('folder/add/', add_folder, name='add-folder'),
    path('tag/add/', add_tag, name='add-tag'),
    path('folder/file/add/', add_folder_files, name='add-folder-files'),
    # Api urls
    url(r'^api/', include('api.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

klazor/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel


class Tag(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'tag'


class Content(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class Item(PolymorphicModel, Content):
    non_polymorphic = models.Manager()
    tag_set = models.ManyToManyField(Tag, blank=True)
    folder = models.ForeignKey('Folder', null=True, blank=True, on_delete=models.CASCADE)

    def type(self):
        return self.__class__.__name__

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'item'
        ordering = [
            'id',
        ]
        base_manager_name = 'non_polymorphic'


class FileItem(Item):
    file = models.FileField(upload_to='files', null=True)

    class Meta:
        db_table = 'file'


class Folder(Content):
    parent = models.ForeignKey('Folder', models.CASCADE, null=True, blank=True, related_name='sub_folder_set')

    def __str__(self):
        return self.name

    def siblings(self):
        result = []
        if self.parent:
            result = [
                folder for folder in self.parent.sub_folder_set.filter(owner=self.owner)
                if folder.id != self.id and folder.id != 1
            ]
        return result

    def ascendants(self):
        result = []
        folder = self
        while folder.id != 1:
            result.append(folder.parent)
            folder = folder.parent

        result.reverse()
        return result

    class Meta:
        db_table = 'folder'
        ordering = [
            'id',
        ]


class Sheet(Item):
    class Meta:
        db_table = 'sheet'


class Cell(PolymorphicModel):
    # non_polymorphic = models.Manager()
    sequence = models.IntegerField(blank=False, null=False)
    sheet = models.ForeignKey(Sheet, on_delete=models.CASCADE)

    def type(self):
        return self.__class__.__name__[:-4]

    class Meta:
        db_table = 'cell'
        ordering = [
            'sequence',
        ]
        # base_manager_name = 'non_polymorphic'


class MediaCell(Cell):
    title = models.CharField(max_length=64, blank=True, null=True)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


class GraphicMediaCell(MediaCell):
    scale = models.FloatField(default=1)

    class Meta:
        abstract = True


class MarkdownCell(Cell):
    text = models.TextField(blank=True, null=True)

    def __str__(self):
        return (self.text[:75] + '...') if len(self.text) > 75 else self.text

    class Meta:
        db_table = 'markdown_cell'


class VideoCell(GraphicMediaCell):

    class Meta:
        db_table = 'video_cell'


class YoutubeCell(GraphicMediaCell):

    class Meta:
        db_table = 'youtube_cell'


class AudioCell(MediaCell):

    class Meta:
        db_table = 'audio_cell'


class FileCell(MediaCell):

    class Meta:
        db_table = 'file_cell'


class ImageCell(GraphicMediaCell):

    class Meta:
        db_table = 'image_cell'


class MultipleChoiceInputCell(Cell):

    class Meta:
        db_table = 'multiple_choice_input_cell'


class NumericalInputCell(Cell):
    answer = models.FloatField(blank=True, null=True)

    class Meta:
        db_table = 'numerical_input_cell'


class OpenEndedInputCell(Cell):
    answer = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'open_ended_input_cell'


class Proposition(models.Model):
    input_cell = models.ForeignKey(MultipleChoiceInputCell, on_delete=models.CASCADE)
    statement = models.TextField(blank=True, null=True)
    is_true = models.BooleanField(default=False)

    class Meta:
        db_table = 'proposition'

templates/includes/components/tiny/course_tiny.html
<div class="tiny card course mb-3" oncontextmenu="openTinyCourseContextMenu(event, {{ course.id }})">
    <i class="fa fa-graduation-cap"></i>
    <div class="card-body">
        <a href="{% url 'course' course.id %}">
            <div class="course-name">
                {{ course.title }}
            </div>
        </a>
        <small class="text-muted ">{{ course.coursepart_set.all.count }} part{{ course.coursepart_set.all.count|pluralize }}</small>
        <br>
        {% include 'includes/components/tiny/created_updated.html' with obj=course %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_course_contextmenu.html' with course=course %}

templates/includes/components/tiny/created_updated.html
{% load humanize %}
<small class="natural-time">
    {% if obj.created_at == obj.updated_at %}
        Created {{ obj.created_at | naturaltime | truncatechars:13 }}
    {% else %}
        Updated {{ obj.updated_at | naturaltime | truncatechars:13 }}
    {% endif %}
    {% comment %}{{ obj.updated_at | naturaltime | capfirst | truncatechars:15 }}{% endcomment %}
</small>

templates/includes/components/tiny/file_tiny.html
{% load filename %}
{% load iconclass %}
<div class="tiny card file mb-3" oncontextmenu="openTinyFileContextMenu(event, {{ file_item.id }})">
    <i class="fa {{ file_item.file.name|iconclass}}"></i>
    <div class="card-body">
        <a href="{{file_item.file.url}}">
            <div class="filename">{{ file_item.file | filename }} </div>
        </a>
        <small class="text-muted ">size : {{ file_item.file.size | filesizeformat}}</small>
        <br>
        {% include 'includes/components/tiny/created_updated.html' with obj=file_item %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_file_contextmenu.html' with file_item=file_item %}

templates/includes/components/tiny/folder.html
<a href="{% url 'folder' folder.id %}">
    <div class="tiny card folder mb-3">
        <i class="fa fa-folder"></i>
        <div class="card-body">
            <div class="folder-name">{{ folder.name }} </div>
            <small class="text-muted ">{{ folder.sheet_set.all.count |add:folder.folder_set.all.count}} items</small>
        </div>
    </div>
</a>

templates/includes/components/tiny/folder_tiny.html
<div class="tiny card folder mb-3" oncontextmenu="openTinyFolderContextMenu(event, {{ folder.id }})">
    <i class="fa fa-folder"></i>
    <div class="card-body">
        <a href="{% url 'folder' folder.id %}">
            <div class="folder-name">{{ folder.name }} </div>
        </a>
        <small class="text-muted ">{{ folder.item_set.all.count |add:folder.folder_set.all.count }} item{{ folder.item_set.all.count |add:folder.folder_set.all.count | pluralize }}</small>
        <br>
        {% include 'includes/components/tiny/created_updated.html' with obj=folder %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_folder_contextmenu.html' with folder=folder %}
{% include 'includes/components/modals/rename_folder.html' with folder=folder %}
{% include 'includes/components/modals/move_folder.html' with folder=folder %}

templates/includes/components/tiny/mooc_course.html
<a href="{% url 'mooc-course' mooc_course.id %}">
    <div class="tiny card mooc-course mb-3">
        <i class="fa fa-book"></i>
        <div class="card-body">
            <div class="course-name">
                {{ mooc_course.title }}
            </div>
            <small class="text-muted ">{{ mooc_course.week_set.all.count }} semaines</small>
        </div>
    </div>
</a>

templates/includes/components/tiny/school_course.html
<a href="{% url 'school-course' school_course.id %}">
    <div class="tiny card school-course mb-3">
        <i class="fa fa-book"></i>
        <div class="card-body">
            <div class="course-name">
                {{ school_course.title }}
            </div>
            <small class="text-muted ">{{ school_course.item_set.all.count}} items</small>
        </div>
    </div>
</a>

templates/includes/components/tiny/sheet.html
<a href="{% url 'sheet' sheet.id %}">
    <div class="tiny card sheet mb-3">
        <i class="fa fa-leaf"></i>
        <div class="card-body">
            <div class="sheet-title">{{ sheet.title }}</div>
            <small class="text-muted ">{{ sheet.content_set.all.count }} contents</small>
        </div>
    </div>
</a>

templates/includes/components/tiny/sheet_tiny.html
<div class="tiny card sheet mb-3" oncontextmenu="openTinySheetContextMenu(event, {{ sheet.id }})">
    <i class="fa fa-leaf"></i>
    <div class="card-body">
        <a href="{% url 'sheet' sheet.id %}">
            <div class="sheet-title">{{ sheet.title }}</div>
        </a>
        <small class="text-muted ">{{ sheet.cell_set.all.count }} cell{{ sheet.cell_set.all.count|pluralize }}</small>
        <br>
        {% include 'includes/components/tiny/created_updated.html' with obj=sheet %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_sheet_contextmenu.html' with folder=folder %}
{% include 'includes/components/modals/move_sheet.html' with sheet=sheet %}

templates/includes/components/tiny/tiny_file.html
{% load filename %}
{% load iconclass %}
<div class="tiny card file mb-3" oncontextmenu="openTinyFileContextMenu(event, {{ file_item.id }})">
    <i class="file fa {{ file_item.file.name|iconclass}}"></i>
    <div class="card-body">
        <a href="{{file_item.file.url}}">
            <div class="filename">{{ file_item.file | filename }} </div>
        </a>
        <small class="text-muted ">size : {{ file_item.file.size | filesizeformat}}</small>
        {% block other_info %}{% endblock %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_file_contextmenu.html' with file_item=file_item %}
{% include 'includes/components/modals/move_file.html' with file_item=file_item %}

templates/includes/components/tiny/tiny_folder.html
<div class="tiny card folder mb-3" oncontextmenu="openTinyFolderContextMenu(event, {{ folder.id }})">
    <i class="fa fa-folder"></i>
    <div class="card-body">
        <a href="{% url 'folder' folder.id %}">
            <div class="folder-name">{{ folder.name }} </div>
        </a>
        <small class="text-muted ">{{ folder.item_set.all.count |add:folder.sub_folder_set.all.count }} item{{ folder.item_set.all.count |add:folder.sub_folder_set.all.count | pluralize }}</small>
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_folder_contextmenu.html' with folder=folder %}
{% include 'includes/components/modals/rename_folder.html' with folder=folder %}
{% include 'includes/components/modals/move_folder.html' with folder=folder %}

templates/includes/components/tiny/tiny_recent_sheet.html
{% extends 'includes/components/tiny/tiny_sheet.html' %}
{% block other_info %}
    <small><a href="{% url 'folder' sheet.folder.id %}">
            <div class="sheet-location-title"> {% if sheet.folder.id == 1 %}<i class="fa fa-home"></i> {% else %}<i class="fa fa-folder"></i>{% endif %} {{ sheet.folder.name}}</div>
        </a></small>
    <span class="recent-info">{% include 'includes/components/tiny/created_updated.html' with obj=sheet %}</span>
{% endblock %}

templates/includes/components/tiny/tiny_sheet.html
<div class="tiny card sheet mb-3" oncontextmenu="openTinySheetContextMenu(event, {{ sheet.id }})">
    <i class="fa fa-leaf"></i>
    <div class="card-body">
        <a href="{% url 'sheet' sheet.id %}">
            <div class="sheet-name">{{ sheet.name }}</div>
        </a>
        <small class="text-muted ">{{ sheet.cell_set.all.count }} cell{{ sheet.cell_set.all.count|pluralize }}</small>
        {% block other_info %}{% endblock %}
    </div>
</div>
{% include 'includes/components/menus/contextmenus/tiny_sheet_contextmenu.html' with folder=folder %}
{% include 'includes/components/modals/move_sheet.html' with sheet=sheet %}